### ISSUE TITLE
Emulate keypad

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-wiegand#4]
Emulate keypad for:
- super password/PIN
- card+PIN

### Notes:
1. https://www.farpointedata.com/downloads/qsg_and_ref/KeypadMode_REF.pdf
2. https://www.keyless.com/wp-content/uploads/2019/01/TProxInstallationManual.pdf
3. https://github.com/uhppoted/uhppoted/issues/40
4. https://nodemcu.readthedocs.io/en/release/modules/wiegand
5. https://github.com/rfidtool/ESP-RFID-Tool

**Comment by twystd** [comment]
Added keypad emulation:
- 4-bit burst mode
- 8-bit burst mode
- card + PIN

Pending release v0.8.7
